spring:
      datasource:
                url: jdbc:mysql://localhost:3306/microservicedbmvc
                driver-class-name: com.mysql.jdbc.Driver
                username: root
                password: root
      jpa:
         hibernate:
           ddl-auto: update
         show-sql: true
         properties:
           hibernate:
             dialect: org.hibernate.dialect.MySQL5Dialect 